### ISSUE TITLE
Page Toc

### ISSUE THREAD

**Issue by stefanwalther** [helpers/helper-toc#1]
Hi,

is it correct that helper-toc only creates a toc if I specify a filename, but NOT from the current file. At least I cannot see an option which would automatically use the current document to create the toc.

Regards
Stefan

**Comment by jonschlinkert** [comment]
correct, since there are technical challenges to getting a helper to render the same string that it's currently embedded in. a better approach is https://github.com/jonschlinkert/template-toc. 

just use that as an assemble middleware
